Carta
UNIZAR-30226-2021-07/web pull request #167
Opened 2021-04-23 14:04 UTC by jmarindiez

Componente carta. Closes #140

2021-04-23 14:38 UTC, marioortizmanero commented
Querido Señor Don José Marín,

Me dirijo a usted respetuosamente para que si es posible, se ponga usted una imagen de perfil en la plataforma en la que nos encontramos. No por entrometerme en sus asuntos ni mucho menos, sino porque considero que adicionalmente sería usted un contruibuidor más respetable en dicho caso. Ruego se ponga al menos una fotografía de Don Lionel Andrés Messi como razón principal de que se le pueda identificar de forma fácil cuando hace un commit o un pull request.

Un cordial saludo y le deseo que pase una tarde agradable,
Mario

2021-04-23 16:39 UTC, jmarindiez commented
Hay tres tipos de cartas:
* Las de la mano: `type=hand`
* Las del cuerpo: `type=body`
* Las de los rivales `type=rival`

2021-04-24 08:53 UTC, FCanfran reviewed
> Querido Señor Don José Marín,
> 
> Me dirijo a usted respetuosamente para que si es posible, se ponga usted una imagen de perfil en la plataforma en la que nos encontramos. No por entrometerme en sus asuntos ni mucho menos, sino porque considero que adicionalmente sería usted un contruibuidor más respetable en dicho caso. Ruego se ponga al menos una fotografía de Don Lionel Andrés Messi como razón principal de que se le pueda identificar de forma fácil cuando hace un commit o un pull request.
> 
> Un cordial saludo y le deseo que pase una tarde agradable,
> Mario

Si la verdad Jose marchando fotito, si no ya te paso yo una del Pirineo. De Messi no, porfa jajajaajaj

2021-04-24 08:53 UTC, FCanfran commented on src/style.css
> +.game-card:hover {
el hover lo haría solo para las cartas de tipo `hand` porque para los otros tipos, en los que la carta puede estar en una pila, el efecto es un poco raro

2021-04-24 08:59 UTC, jmarindiez commented on src/style.css
> +.game-card:hover {
Estoy de acuerdo.

2021-04-24 10:33 UTC, xzebra requested changes
![image](https://user-images.githubusercontent.com/20362769/115955724-a6aafb00-a4f8-11eb-9c9c-238782135eb7.png)

Esta carta no sería posible no? El icono que aparece es el de medicina pero realmente es un órgano. He mirado las assets y la carta correspondiente no es de tipo medicina, no se si es por un tema de pruebas o por que.
```
  {
    "name": "Estómago",
    "description": "¡Es tu estómago!",
    "image": "cards/cuerpo_estomago.svg",
    "type": "organ",
    "color": "green",
    "total": 5
  },
  ```

2021-04-24 10:33 UTC, xzebra commented on src/components/App.js
> +        {/* TODO: DEJAR DESCOMENTADO */}
se os ha colao

2021-04-24 11:41 UTC, jmarindiez commented on src/components/App.js
> +        {/* TODO: DEJAR DESCOMENTADO */}
> ![image](https://user-images.githubusercontent.com/20362769/115955724-a6aafb00-a4f8-11eb-9c9c-238782135eb7.png)
> 
> Esta carta no sería posible no? El icono que aparece es el de medicina pero realmente es un órgano. He mirado las assets y la carta correspondiente no es de tipo medicina, no se si es por un tema de pruebas o por que.
> 

No entiendo muy bien a que te refieres. A que la carta esta mal hecha? O a que no es posible tener esa carta en tu mano?

2021-04-24 15:54 UTC, xzebra commented on src/components/App.js
> +        {/* TODO: DEJAR DESCOMENTADO */}
Vale nada perdon, es un problema en el asset. El icono no debería ser una cruz

2021-04-24 15:55 UTC, xzebra commented on src/components/App.js
> +        {/* TODO: DEJAR DESCOMENTADO */}
aun asi estaba reteniendo esto por el TODO de https://github.com/UNIZAR-30226-2021-07/web/pull/167#discussion_r619641383

2021-04-24 18:34 UTC, xzebra approved these changes

2021-04-24 18:34 UTC, merged