fixed players on game provider
UNIZAR-30226-2021-07/web pull request #200
Opened 2021-05-10 16:59 UTC by FCanfran

2021-05-11 22:20 UTC, FCanfran commented
Ya está solucionado lo del abandono de un jugador y su reemplazo por ia

2021-05-12 10:29 UTC, xzebra requested changes
Cuando un jugador es expulsado, obtengo este error en uno de los clientes (no el expulsado).

![image](https://user-images.githubusercontent.com/20362769/117960664-81eabc00-b31d-11eb-8100-d80c3825c853.png)

Además, el jugador expulsado parece no enterarse de nada y cree seguir en la partida.

2021-05-12 10:29 UTC, xzebra commented
Ahora investigo más

2021-05-12 10:35 UTC, FCanfran commented
Creo que es porque no limpio los playerRef en el return, ahora pruebo a ver.

2021-05-12 10:39 UTC, xzebra commented
Se obtiene lo siguiente cuando el jugador 3 es expulsado:

![image](https://user-images.githubusercontent.com/20362769/117961889-ea866880-b31e-11eb-8773-b153a074737b.png)

Pero ahora no se si deberia estar devolviendo un jugador adicional con el `is_ai = true`

2021-05-12 10:46 UTC, FCanfran commented
A bueno, pues eso ya no se, lo que si he hecho es limpiar el playersRef, que Jose me había dicho que se quedaban los datos viejos al volver a entrar a una partida. Mira a ver ahora de todas formas, aunque no creo que tenga que ver.

2021-05-12 11:26 UTC, xzebra commented
Falta hacer que el expulsado deje de creer que sigue jugando
![image](https://user-images.githubusercontent.com/20362769/117967691-a054b580-b325-11eb-9758-9ffed30c79ba.png)

2021-05-12 11:58 UTC, xzebra approved these changes

2021-05-12 12:01 UTC, xzebra commented
Te la acepto y mergeo pero falta hacer #201, ya la hareis cuando se arregle en backend.

2021-05-12 12:01 UTC, merged