Popup para la creación de partidas privadas
UNIZAR-30226-2021-07/web pull request #46
Opened 2021-03-26 13:01 UTC by jmarindiez

2021-03-26 16:03 UTC, jmarindiez commented
Para revisarlo mas comodamente podeis poner este `App.js`:

```javascript
import React, { useState } from 'react';

import Menu from './Menu';
import Login from './Login';

import { openPrivatePopup } from './PrivatePopUp';

import './App.css';
import 'bootstrap/dist/css/bootstrap.min.css'

function App() {
  const [logged, setLogged] = useState(false);

  return (
    <div className="App">
      {logged ? <Menu /> : <Login onLogin={() => setLogged(true)} />}
      <button onClick={() => openPrivatePopup()}> PopUp</button>
    </div>
  );
}

export default App;
```

2021-03-26 19:37 UTC, xzebra requested changes

2021-03-26 19:37 UTC, xzebra commented on src/PrivatePopUp.js
> +export default function PrivatePopup({ children }) {
El popup genérico estaba para reutilizarse y que solo tuvierais que escribir el cuerpo de esto. De hecho, el atributo `children` que arrastras es lo que va dentro de las etiquetas en un componente. Podrías haber hecho algo como:
```js
... function PrivatePopup() {
    return (
        <Popup>
            <Row className="d-flex justify-content-center">
            <p>
              Introduce el código de partida y <br></br>
              comienza a jugar con tus amigos.
            </p>
          </Row>
          <Row className="d-flex justify-content-between">
            <input className= "code-box"
              type="text"
              size = "8"
              minLength="4"
              maxLength="8"
              placeholder="Código"
            ></input>
            <Button
              className="btn btn-primary"
              onClick={PopupboxManager.close}
            >
              CONFIRMAR
            </Button>
          </Row>
        </Popup>
    )
}
```

2021-03-27 18:22 UTC, xzebra approved these changes

2021-03-27 18:22 UTC, xzebra commented on src/JoinGamePopup.test.js
> +test("check input is correct", () => {
Técnicamente estás seleccionando el elemento que contiene el texto:
```
Introduce el código de partida y
comienza a jugar con tus amigos.
```

2021-03-27 18:22 UTC, xzebra commented on src/JoinGamePopup.test.js
> +test("check input is correct", () => {
Podrías usar `getByPlaceholderText` en luegar de `getByText` para seleccionar el campo de texto.

2021-03-27 18:51 UTC, merged