Popup creador de la partida
UNIZAR-30226-2021-07/web pull request #47
Opened 2021-03-26 16:16 UTC by jmarindiez

PopUp que proporciona el codigo de la partida para ser compartido con resto de jugadores

2021-03-26 16:41 UTC, xzebra requested changes, later dismissed

2021-03-26 16:41 UTC, xzebra commented on src/CreateGamePopup.test.js
> +import CreateGamePopUp from "./CreateGamePopUp";
Lo has llamado `Popup`, no `PopUp`

2021-03-26 17:08 UTC, jmarindiez commented on src/CreateGamePopup.test.js
> +import CreateGamePopUp from "./CreateGamePopUp";
Falla el ultimo test, y no se como arreglarlo. Sospechaba del `readOnly` del codigo, pero parece que no es eso

2021-03-26 19:06 UTC, xzebra commented on src/CreateGamePopup.test.js
> +import CreateGamePopUp from "./CreateGamePopUp";
No encuentra el código porque lo has puesto como placeholder.

2021-03-26 19:22 UTC, jmarindiez commented on src/CreateGamePopup.test.js
> +import CreateGamePopUp from "./CreateGamePopUp";
Ya ya, es que yo lo queria como placeholder, pero vaya... si no se puede da igual

2021-03-27 18:27 UTC, xzebra approved these changes, later dismissed

2021-03-27 18:27 UTC, xzebra commented on src/CreateGamePopup.js
> +          placeholder={code}
No tiene mucho sentido ponerlo como `placeholder`. El `placeholder` es el texto que se muestra para darle una pista al usuario sobre lo que escribir. `value` es lo que contiene el campo de texto`

2021-03-27 18:30 UTC, xzebra requested changes

2021-03-27 18:30 UTC, xzebra commented on src/CreateGamePopup.js
> +          placeholder={code}
No entiendo por qué quieres usar `placeholder`. El `placeholder` da una pista al usuario sobre lo que tiene que escribir en ese campo de texto; y el usuario no deberia tener que escribir nada. `value` es lo que contiene el campo de texto como tal.

2021-03-28 18:01 UTC, xzebra approved these changes

2021-03-28 18:01 UTC, merged